language: node_js
services:
  - docker
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_install:
install:
  - npm install
before_script:
script:
  - npm run build
  - npm test
  - npm run coveralls
  - npm run codacy-coverage
after_success:
after_failure:
before_deploy:
deploy:
after_deploy:
after_script: