language: node_js
node_js:
  - "8"
before_install:
install:
  - npm install
  - npm run build
before_script:
script:
  - npm test
after_success:
after_failure:
before_deploy:
deploy:
after_deploy:
after_script: